### ISSUE TITLE
Move the documentation to a wiki

### ISSUE THREAD

**Issue by CoolOppo** [mridgers/clink#237]
Currently, the documentation is stored in the [docs](https://github.com/mridgers/clink/tree/b30d62b1759f8ae7b782880f9510f0dfe10b7c26/docs) folder. It would be much better-suited for a GitHub wiki; people are free to contribute, and it is much easier to browse the pages.

Another possibility is moving some of the information to the `README.md` file as well as placing a link to the wiki in order to make it more apparent that there _is_ additional documentation available.

**Comment by limeblack** [comment]
I'm voting no on this unless someone can give a very compelling.  I think this is fairly stagnant in terms of chances and a lot of the wiki capability isn't need.

**Comment by mridgers** [comment]
Part of the reason is that documentation is where it is is because it is used to auto-generate the documentation that's included in releases. I'd also like to further improve that to generate the Lua API documentation from source too. As such I'm adverse to moving to a wiki as it would add a lot of overhead keeping the two in sync.
