### ISSUE TITLE
New environment variables not picked up....

### ISSUE THREAD

**Issue by Uxorious** [mridgers/clink#291]
Using Clink 0.4.3 I have observed a strange bug re. newly added environment variables.

Do something like the following:
1) Run cmd/clink
2) set
    Look at the list of variables ...
3) exit
4) Install a program (in my case an msi file) which adds system environment variables.
5) Run cmd/clink
6) set
    Look at the list of variables ... the variables added in #4 are not there
7) exit
8) Go to the control panel environment variable settings, and simply click OK (or add an extra variable)
9) Run cmd/clink
10) set
    Look at the list of variables ... now all the variables are there

Does this make any sense?

**Comment by mridgers** [comment]
Yup, makes sense. This is the fault of a poorly behaving installer for the program you've installed and not Clink. When an process modifies the system's environment variable it should broadcast the WM_SETTINGCHANGE message otherwise the environment changes do not propagate. When you go via the control panel and click OK you implicitly broadcast this message which is why everything then appears to work fine.

Clink's installer can also modify the system environment which is why the installer script has [this line](https://github.com/mridgers/clink/blob/master/installer/clink.nsi#L171) in it.

[MSDN docs for reference](https://msdn.microsoft.com/en-us/library/windows/desktop/ms725497(v=vs.85).aspx)

**Comment by Uxorious** [comment]
Thanks for the info - I'll relay that info to the program vendor in question!

**Comment by Uxorious** [comment]
Just to make sure I understand:
Even if you QUIT the command prompt and open a new one, it will not pick up any changed ENV variables unless a WM_SETTINGCHANGE message was sent?

Would it be possible to always get the latest ENV variables when a console is started?
This would match the default commandline behavior better...
