### ISSUE TITLE
How do I get tab completion on a filename in a directory

### ISSUE THREAD

**Issue by idvorkin** [mridgers/clink#313]
With cmd, if I launch a file name, it opens with the default program.  For example to open foo.txt in notepad I'd do the following: 

    C:\temp>dir *.txt

    01/21/2015  12:18 PM                87 commands.txt
    02/13/2015  08:46 AM                56 foo.txt
    
    C:\temp>f <tab> <enter>

However, when I do this in clink, I don't get completion for foo.txt what's the right way to handle this?

**Comment by mridgers** [comment]
This is by design. By default Clink completes executables in the path for the first word. If the line being edited starts with whitespace it will complete files. This behaviour can be customised to your preferences using "clink set". So to use your example above with default Clink settings;

```
C:\temp>f <tab> <tab>
find.exe    findstr.exe    format.com   fc.exe

C:\temp>    f <tab>
C:\temp>    foo.txt
```

There's more details in the recent issue #311

**Comment by idvorkin** [comment]
Starting with Space was what I was looking for - thanks!
