### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by murilolobato** [mridgers/clink#322]
Does clink has a automatic update feature? If I install clink via installer, will I be notified when a new release be available? If not, how should I proceed on future updates? Just install the new version over the existant files?

**Comment by mridgers** [comment]
There's no update check in Clink - I've thought about it but I'm a bit apprehensive because Clink is injected into cmd.exe and an update check would mean that cmd.exe has to access the Internet. This could be a security concern for some.

You can watch the repository and Github will send you [notifications](https://help.github.com/articles/about-notifications/) when new releases are published.
