### ISSUE TITLE
Clink partially reprints prompt with newline on resize

### ISSUE THREAD

**Issue by ElArtista** [mridgers/clink#352]
When clink is injected in a Console emulator (like ConEmu or Console2) and prompt contains a newline (for example do 'prompt $P$_$G') and the Console is resized, clink partially reprints prompt.

See here for screenshots:
http://superuser.com/questions/978140/why-is-my-prompt-reprint-on-horizontal-conemu-resize

EDIT: Using clink 0.4.5

**Comment by mridgers** [comment]
Resizing is a little bit flakey altogether actually, both a combination how Windows' console behaves differently from VT100-like consoles that Readline's designed for, and because of a few bugs in Readline.

I occasionally put some time into getting resizing perfect, but hadn't consider the case of a multi-line prompt. Thanks for bringing that to my attention.

**Comment by ElArtista** [comment]
You should note that in previous version 0.4.4 resizing with multiline prompt worked flawlessly.

**Comment by mridgers** [comment]
Oh, I see. In that case, I broke something :)
