### ISSUE TITLE
clink inserting carets (^) into doskey macro git log output

### ISSUE THREAD

**Issue by gigadude** [mridgers/clink#358]
I have a doskey macro which looks like:

    gl=git log --decorate --pretty="%C(auto)%h%d %s %C(black bold)%an%C(reset)" $*

It was working fine with 0.4.4, but I upgraded to 0.4.5 to be able to use https://github.com/vladimir-kotikov/clink-completions and now some (but not all) escape characters are prefixed with a `^` character:

![image](https://cloud.githubusercontent.com/assets/1423804/10527682/a743eb2e-7346-11e5-918b-00dc7ca428ad.png)

Running the identical command directly (without the doskey macro expansion) works as usual.

Downgrading back to 0.4.4 makes it go away but breaks the clink-completions scripts. I also tried the same upgrade on another machine which doesn't have the scripts installed and it has the same problem, so I don't think it's anything to do with clink-completions.

I'm on Win8.1 x64 using a bare command shell with ConEmu (ConEmuBuild=151006) + clink, git version 2.6.1.windows.1

**Comment by gigadude** [comment]
Going to see if https://github.com/mridgers/clink/commit/17b807c637d2b8fb47ef5719f91490833aaf9eba fixes the issue...

**Comment by vladimir-kotikov** [comment]
@gigadude, could you please add a bit more details about
> Downgrading back to 0.4.4 makes it go away but breaks the clink-completions scripts
I was using them with clink@0.4.4 without any issues.

**Comment by gigadude** [comment]
I used the installer 20150923_1abb57 from the dropbox link and this problem is resolved.

@vladimir-kotikov your scripts don't seem to be working with 0.4.4 (at least I'm not getting git checkout <branch> to expand), which is what prompted my clink upgrade in the first place. 0.4.5 works but has the bug which 17b807c fixes. BTW git sub-commands aren't expanding for me, haven't tried to debug that (branch expansion is all I really wanted)

**Comment by vladimir-kotikov** [comment]
Could you please post that Dropbox link, so i can investigate it?

**Comment by Stanzilla** [comment]
@vladimir-kotikov https://www.dropbox.com/sh/hqbrpkf0dpmmizq/gGX4XWAWIA

**Comment by vladimir-kotikov** [comment]
Thanks.

**Comment by mridgers** [comment]
The extra `^` characters came from changes I'd made previously so that doskey macros like `cd=cd $* $T title ^%cd^%` worked as expected. Windows will actually return multiple lines when reading input for this macro. Clink however was escaping the `%` characters (cmd.exe's uses `^` as the escape character) and returning the macro as one single line. As you've found, the commit linked above has Clink do things the proper way.

@gigadude; you might want to consider escaping the `%` in your macro (e.g. `^%`) as cmd.exe uses `%` for environment variable expansion. You might get odd results if you do `set an=foobar` before running doskey to set your macro. Pretty minimal think though really.

Apologies for not replying sooner - been a bit busy.
