### ISSUE TITLE
A Clink window flashes twice and takes focus

### ISSUE THREAD

**Issue by seece** [mridgers/clink#359]
I'm not entirely sure if this is a fault of Clink or just some other program acting weird, but every once in a while two empty command prompts open with some ten seconds after each other with the title `clink_x86.exe inject --profile "~\clink"`. This is pretty annoying since it takes the focus away from the current window. Everytime this has happened I've had some Clink command windows open in ConEmu 150910.

Clink version is 0.4.5.

**Comment by mridgers** [comment]
Are you running `clink.bat` without any arguments? This [bootstraps](https://github.com/mridgers/clink/blob/master/clink/loader/clink.bat#L77) cmd.exe with Clink loaded into it (to avoid having two cmd.exe processes running) and can cause a console windows to very briefly appear.

**Comment by seece** [comment]
I've never invoked it manually, I just open command prompts via ConEmu that are then minimized to the task bar. If some unrelated program runs periodically commands through invoking `cmd.exe` then having Clink installed shouldn't make any extra windows appear, right?

**Comment by mridgers** [comment]
Clink itself never spawns new processes. The exception is `clink.bat` but only if you run it without any arguments, which you say you're not doing. The `clink_x86.exe ...` in the title is a useful clue though, as I believe that is the Clink autorun entry. I presume you have installed Clink and selected that option?

At this point I can't really say that Clink is at fault here - it's just active because of the autorun entry. I think the best diagnosis would be to see what the command line is of these mysterious cmd.exe processes. If they stay around for long enough you can get that from Windows' task manager.

**Comment by seece** [comment]
Thanks for your reply. Seems like it's not related to Clink, so closing this.

**Comment by seece** [comment]
Looks like the problem was Akamai NetSession Interface trying to run `installer_no_upload_silent.exe` periodically.

**Comment by mridgers** [comment]
Awesome. Pleased to see that you got to the bottom of it.
