### ISSUE TITLE
Virus warning for Clink 4.6

### ISSUE THREAD

**Issue by joce** [mridgers/clink#369]
Attempting to run the installer clink_0.4.6_setup.exe triggers my antivirus (Avira):

![clink46_virus_warning](https://cloud.githubusercontent.com/assets/80361/12043688/67f21b9a-ae55-11e5-9285-409e396126da.png)

It appears to be infected with "HEUR/APC (Cloud)". Is the dev's machine infected? Could it be a false positive? Please advise.

**Comment by mridgers** [comment]
This is a false positive. The "HEUR" part is indicating that Avira's heuristic scanner has triggered for some reason. There is a very very slim chance that it is because the installer is in your `Downloads` directory because NSIS is vulnerable to drive-by DLL hijacking - try moving it elsewhere.

VirusTotal total is not reporting any issues for any of Clink's executables. Here's the links;

[clink_0.4.6_setup.exe](https://www.virustotal.com/en/file/a1500257afd6e5728368a1d24f3ba62323fe482f40a63f081e1b8b1a16f69398/analysis/1451466693/)
[clink_x64.exe](https://www.virustotal.com/en/file/298e7106112f799e6d6de17cc93ec0060ac8188340fa9a6fe979a8aba75c14bc/analysis/1451466928/)
[clink_x86.exe](https://www.virustotal.com/en/file/e23373b46fbaf76e0216adbed4472f3968b1439bd07374c42547efc5614fafec/analysis/1451466991/)
[clink_dll_x64.dll](https://www.virustotal.com/en/file/52cc06a31e74d6488dc0292be8aad1799a37624dee7d2ba7014a52e948cadc0a/analysis/1451467088/)
[clink_dll_x86.dll](https://www.virustotal.com/en/file/07fdef4e9345738553a19079d7464060501acb65fc74e429db0c35fe251b0f96/analysis/1451467159/)
