### ISSUE TITLE
PATH with & results in commands being executed

### ISSUE THREAD

**Issue by dusenyao** [mridgers/clink#378]
The following is a segment from my PATH information, 

`...;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5\Doctrine extensions for PHP\;C:\Program Files (x86)\Heroku\bin;...`

when I run` echo %PATH%`, `MYSQL `command is being executed, while running the command `PATH `will display the `PATH `properly.

**Comment by mridgers** [comment]
This has nothing to do with Clink. It is expected behaviour from cmd.exe for it to expand the %envvar% prior to executing the line. The following does exactly what you've noticed in vanilla `cmd.exe`;

```
D:\>md "a&dir x"
D:\>set path=a^&dir x;%path%
D:\>echo %path%
a
The system cannot find the path specified.
```

Essentially, whoever is responsible for adding a path that contains an `&` character should have enclosed it in quotes.
