### ISSUE TITLE
Clink prompt retains history items when using arrow keys to cycle through history

### ISSUE THREAD

**Issue by Avinm** [mridgers/clink#387]
For some history items clink retains the first 8 characters in the prompt when cycling the history with arrow keys. The retained characters wont go away with backspace and would seem to have become part of the PS1. Hitting enter to bring up the next line is the only way to get rid of these 8 sticky characters. Using Clink 0.4.7 on Win7 x64

**Comment by doraeric** [comment]
Same problem.
I guess it happens when there are some specific utf-8 texts. I have found this one "σ".
The WideCharToMultiByte function return its width as 2, but it is actually one column wide when displayed.
Here's the image. I pressed `↑` and `↓` to show histories in first line.
I pasted 'σ' and pressed `Backapace` in the second line.
[http://imgur.com/rhVS3Pm](http://imgur.com/rhVS3Pm)

**Comment by baubbelayponge** [comment]
Not sure if it's linked to utf-8 characters.

My recent history has items like "git clone http://myproject" and "rm -rf myfolder" and as soon as I get to the second item in history, I have the bug.

**Comment by techeverri** [comment]
I have the same problem, but using Clink v0.4.6 on Win10 x64.

**Comment by Avinm** [comment]
Seems to be related to having special chars in your $PROMPT, my prompt currently is

**Comment by Avinm** [comment]
Could you release a build with this fix?

**Comment by w1mb0r** [comment]
Can you please release a build with this fix?

**Comment by w1mb0r** [comment]
release 0.4.8 was released on july 13. works great; issue is resolved.
thanks.
