### ISSUE TITLE
Hybrid completion, DOS-style *WORD* ?

### ISSUE THREAD

**Issue by libove** [mridgers/clink#391]
One thing which DOS/Windows does nicely about filename completions which I'd like to be able to add to clink, is the ability to wildcard then TAB match.

e.g. If I have some files in the current directory with names
AFOO1
AFOO2
BFOO3
CFOO4

I'd like to be able to type " *FOO*"{TAB} and have clink list/complete/cycle through those four file names.
Presently, the only way to get any of those filenames to complete (unless I'm missing it) is to explicitly type the leading A, B or C character. When the commonality is NOT at the start of the filename and the directory has many files, Windows' *WORD* trick would be nice.

thanks, and thanks very much for clink - it rocks!

**Comment by mridgers** [comment]
Clink uses Readline for line editing and completion and what your proposing isn't something that Readline supports. I have however been slowly working on a version of Clink where Clink does the completion instead of using Readline. Part of my vision is to support fuzzy completion, similar to Sublime or Vim's Ctrl-P plugin. With this, typing FOO would work much like you describe.

**Comment by vladimir-kotikov** [comment]
> Part of my vision is to support fuzzy completion
@mridgers, it'd be awesome! I was looking into doing this in lua but it appeared that this is impossible due to some readline issues.

**Comment by glenncarr** [comment]
@mridgers I'd love to see some type of fuzzy completion as well - unfortunately, I've grown very dependent on using completion such as _msbuild *j<tab>_ to kick off builds, and _np partial*.cs_ to edit files.
