### ISSUE TITLE
When the cmd.exe is called, cmd.exe crashes

### ISSUE THREAD

**Issue by Cool-Pan** [mridgers/clink#475]
I wrote a AutoHotKey program, specifying a combination key, when the combination key was pressed, cmd.exe was called, and then cmd.exe crashed.

Only a new version will have this problem, the old version will not.

`OS:Windows 10 Enterprise 2016 LTSB (x64)`

**Comment by Cool-Pan** [comment]
OS    : Windows 10 Enterprise 2016 LTSB (x64)
Clink : v1.0.0a0

**Comment by anonymous2ch** [comment]
You need to remove the process architecture check from clink.bat

**Comment by tomasorti** [comment]
> You need to remove the process architecture check from clink.bat

I am commenting it, though still getting the crash...

![clink-crash](https://user-images.githubusercontent.com/2485147/51807357-12547e00-2286-11e9-9966-e5c1635a6975.png)

**Comment by anonymous2ch** [comment]
I suggest pressing that debug button, since you compiled your version of clink yourself, does that problem persist with official 0.4.9 build?

**Comment by tomasorti** [comment]
That problem appears on **master** branch, tag **1.0.0.a1**, not on branch **v0.4.9**.  
Btw, I am already using ConEmu.  
And also installed [Git for Windows](https://github.com/git-for-windows) stuff.  
It has almost the same apps as GOW but more recent versions.    
I install everything through [scoop](https://scoop.sh/), which saves some time.

Which is the point on hitting `Debug` button?

![image](https://user-images.githubusercontent.com/2485147/51841606-58a1ef80-230f-11e9-8cd6-d60fea7896a2.png)

Am I able to troubleshoot anything here?

**Comment by anonymous2ch** [comment]
Well, i've successfully built clink from master branch. The x86 version crashes on inject, the x64 version injects fine, but terminal stops recognizing any non-latin characters I press on keyboard. Unfortunately I'm not a C* expert so master branch is plainly unusable for me just as it was a year ago. Who needs terminal without UTF-8 support. I'm sticking to 0.4.9 for now...

**Comment by tomasorti** [comment]
Well, I would not mind to spend some time troubleshooting this.
I am building it with VS2017, though as I showed `clink.bat` crashes on *master* branch.  

[This other issue](https://github.com/mridgers/clink/issues/510) is driving me nuts...  
Since clink works fine in a fresh install on other computer, but on mine is not.
I have uninstalled it, installed it again, compiled from source...
But none of them fix the ENTER issue I am experiencing.  
And it is kind of annoying..

**Comment by anonymous2ch** [comment]
Well, i don't have that problem with double enter, I bet the problem is caused by modules, loaded into cmd.exe. Here's a picture of mine, they don't cause that, so are probably safe, try to double check & unload those of yours which look suspicious.
![image](https://user-images.githubusercontent.com/11248668/51864632-59f60b00-2355-11e9-9c4d-576315eab1fc.png)

**Comment by tomasorti** [comment]
I just found it...  
A `.inputrc` was created without noticing it.  
That was the cause of the misbehavior.  

Btw, where does that image come from?  
It looks like a `Task Manager` extended window...  
Which application is it?

**Comment by anonymous2ch** [comment]
That is [ProcessHacker](https://processhacker.sourceforge.io)

**Comment by tomasorti** [comment]
Wow! Did not know about it!  
I am currently using Process Explorer, but this one seems better.  
I am back to Windows since 5 years on Ubuntu.  
Nice to find new tools like this one.  
Thank you!

**Comment by tomasorti** [comment]
Ok, I just compiled ***master*** branch, tag ***1.0.0.a1***, and it is not crashing.  
So it seem it is working, though I do not know how this version improves v0.4.9.  
Anyway, why is this issue opened? It should probably be closed.
