### ISSUE TITLE
Failed to compile in VS 2017

### ISSUE THREAD

**Issue by Maximus5** [mridgers/clink#515]
Latest commit: 823d841bc5c38a83c3cc0991c1f3ff8099d83fb5
Solution files generated by `Premake5 vs2017`.

```
1>...\clink\clink\terminal\src\win_screen_buffer.cpp(165): error C2220: warning treated as error - no 'object' file generated
1>...\clink\clink\terminal\src\win_screen_buffer.cpp(165): warning C4838: conversion from 'int' to 'SHORT' requires a narrowing conversion
1>...\clink\clink\terminal\src\win_screen_buffer.cpp(178): warning C4838: conversion from 'A' to 'SHORT' requires a narrowing conversion
```

and

```
1>...\clink\clink\terminal\src\win_screen_buffer.cpp(178): error C2220: warning treated as error - no 'object' file generated
1>...\clink\clink\terminal\src\win_screen_buffer.cpp(178): warning C4838: conversion from 'A' to 'SHORT' requires a narrowing conversion
```

**Comment by garoto** [comment]
You must be aware by now that **mridgers** is AWOL right?

**Comment by CollinChaffin** [comment]
Was just about to open an issue myself asking if this is even being actively developed anymore in some other private repo etc. considering not a single commit here in over half a year, nor even a single comment from the lead developer.

**Comment by WSLUser** [comment]
@Maximus5 I would suggest forking the master branch and bringing it to ConEmu and integrate it or work with Cmder since that project ties ConEmu and Clink together. I actually wonder if it might not be best to merge all 3 projects together. Usually Cmder is used once a person is made aware of it. It especially helps with using the win32 opens project on lower versions of Windows (7 and 8). I know I'd personally love to see all 3 projects being actively developed and optimized for integration for use on Windows regardless of OS version.

**Comment by Maximus5** [comment]
Fixed by https://github.com/Maximus5/clink/commit/ff3759badd36e17d0eb99c58b513044b40b49cb1
