### ISSUE TITLE
VS Code not capturing std output

### ISSUE THREAD

**Issue by duzenko** [mridgers/clink#542]
I have an Angular project with the `ng build --aot --watch` script that normally redirects the std output into the integrated terminal.

With CLink I noticed it's often empty. The terminal allocates the space as if there's a text there but nothing actually shows.

Clink
![image](https://user-images.githubusercontent.com/1481807/85105198-b8ee4580-b212-11ea-9a30-4816d28f947a.png)

Powershell

![image](https://user-images.githubusercontent.com/1481807/85105387-213d2700-b213-11ea-8a20-b76ced1ee876.png)

**Comment by chrisant996** [comment]
Hi, this original fork of Clink has been abandoned for a few years.  Can you please try with the [chrisant996 fork](https://github.com/chrisant996/clink)?  That's where forward development is happening, and it may or may not have already solved the problem.

If the same problem occurs with the new Clink fork, please create a new issue there, and please try to isolate steps that will reproduce the problem using a stock installation of VSCode and Clink (i.e. without requiring Angular).  If you're tried to isolate steps that don't require Angular and it _only_ happens with Angular, then that will also be useful information to know.  (And since I've never used Angular, you'll need to provide additional information to teach me how to reproduce the issue.)

Thanks!
