### ISSUE TITLE
Mouse click

### ISSUE THREAD

**Issue by Remiol** [mridgers/clink#572]
What a great idea!
Great that I can now use the usual commands again.

It's just that... I can't use my mouse now.
Clicking with my mouse in the middle of the line (to insert some text) no longer works.
How can I make my mouse work as before?

**Comment by chrisant996** [comment]
How were you getting mouse clicking to move the text insertion point?  That has never worked in CMD in ConHost, nor in Windows Terminal.

**Comment by chrisant996** [comment]
But also, this repo has been abandoned for years.  Go to https://github.com/chrisant996/clink instead.

**Comment by Remiol** [comment]
Yes, I could do it in Windows Console and indeed I'm using mostly ConEmu. 
Agree it doesn't work in Windows Terminal. 

ps: is there a way to temporary disable clink? 

Sorry, I'll use the christant996 repo next time.

**Comment by chrisant996** [comment]
> Yes, I could do it in Windows Console and indeed I'm using mostly ConEmu. 
> Agree it doesn't work in Windows Terminal. 
> 
> ps: is there a way to temporary disable clink? 
> 
> Sorry, I'll use the christant996 repo next time.

Can you clarify what you have in mind for "temporarily disable Clink"?
And what is an example of a scenario where you want to do so?

**Comment by Remiol** [comment]
Just to use the click within the text function once in a while or when there is a hotkey conflict.

It would be nice that there is something like toggle Clink --> enable/disable Clink

**Comment by chrisant996** [comment]
You mean a key binding to disable/enable Clink?

That's not really possible:  Clink can't respond to a key binding to enable Clink when Clink is disabled.  It's disabled, so it's not running.

Also, disabling (or enabling) Clink means exiting the current input prompt, telling CMD that a blank line was entered, showing a new prompt on a new line, and then letting the OS or ConEmu handle input for the next input line, instead of Clink.

If the reason for disabling/enabling Clink is to allow mouse input on the fly, that won't work at all.

I'm exploring what options exist for allowing mouse input in Windows Terminal, ConEmu, and plain console windows.  If a terminal supports certain DECSET escape codes for mouse tracking then it might be possible to get this to partially work, but probably at the expense of losing all mouse features from the terminal program itself (such as click+drag to select text and copy it to the clipboard).

**Comment by chrisant996** [comment]
@Remiol you can close this.  I created an issue in the current repo.

**Comment by Remiol** [comment]
Thank you for your support 👍
